// Auto-generated by dump_syscall_id.py.  Do not modify.

package bad

type SyscallId struct {
	Name   string
	Number int
}

func GetSyscallIdByNumber(num int) (SyscallId, bool) {
	for _, id := range syscallIds {
		if id.Number == num {
			return id, true
		}
	}

	return SyscallId{}, false
}

func GetSyscallIdByName(name string) (SyscallId, bool) {
	for _, id := range syscallIds {
		if id.Name == name {
			return id, true
		}
	}

	return SyscallId{}, false
}

func (id SyscallId) String() string {
	return id.Name
}

var syscallIds = []SyscallId{
	{
		Name:   "read",
		Number: 0,
	},
	{
		Name:   "write",
		Number: 1,
	},
	{
		Name:   "open",
		Number: 2,
	},
	{
		Name:   "close",
		Number: 3,
	},
	{
		Name:   "stat",
		Number: 4,
	},
	{
		Name:   "fstat",
		Number: 5,
	},
	{
		Name:   "lstat",
		Number: 6,
	},
	{
		Name:   "poll",
		Number: 7,
	},
	{
		Name:   "lseek",
		Number: 8,
	},
	{
		Name:   "mmap",
		Number: 9,
	},
	{
		Name:   "mprotect",
		Number: 10,
	},
	{
		Name:   "munmap",
		Number: 11,
	},
	{
		Name:   "brk",
		Number: 12,
	},
	{
		Name:   "rt_sigaction",
		Number: 13,
	},
	{
		Name:   "rt_sigprocmask",
		Number: 14,
	},
	{
		Name:   "rt_sigreturn",
		Number: 15,
	},
	{
		Name:   "ioctl",
		Number: 16,
	},
	{
		Name:   "pread64",
		Number: 17,
	},
	{
		Name:   "pwrite64",
		Number: 18,
	},
	{
		Name:   "readv",
		Number: 19,
	},
	{
		Name:   "writev",
		Number: 20,
	},
	{
		Name:   "access",
		Number: 21,
	},
	{
		Name:   "pipe",
		Number: 22,
	},
	{
		Name:   "select",
		Number: 23,
	},
	{
		Name:   "sched_yield",
		Number: 24,
	},
	{
		Name:   "mremap",
		Number: 25,
	},
	{
		Name:   "msync",
		Number: 26,
	},
	{
		Name:   "mincore",
		Number: 27,
	},
	{
		Name:   "madvise",
		Number: 28,
	},
	{
		Name:   "shmget",
		Number: 29,
	},
	{
		Name:   "shmat",
		Number: 30,
	},
	{
		Name:   "shmctl",
		Number: 31,
	},
	{
		Name:   "dup",
		Number: 32,
	},
	{
		Name:   "dup2",
		Number: 33,
	},
	{
		Name:   "pause",
		Number: 34,
	},
	{
		Name:   "nanosleep",
		Number: 35,
	},
	{
		Name:   "getitimer",
		Number: 36,
	},
	{
		Name:   "alarm",
		Number: 37,
	},
	{
		Name:   "setitimer",
		Number: 38,
	},
	{
		Name:   "getpid",
		Number: 39,
	},
	{
		Name:   "sendfile",
		Number: 40,
	},
	{
		Name:   "socket",
		Number: 41,
	},
	{
		Name:   "connect",
		Number: 42,
	},
	{
		Name:   "accept",
		Number: 43,
	},
	{
		Name:   "sendto",
		Number: 44,
	},
	{
		Name:   "recvfrom",
		Number: 45,
	},
	{
		Name:   "sendmsg",
		Number: 46,
	},
	{
		Name:   "recvmsg",
		Number: 47,
	},
	{
		Name:   "shutdown",
		Number: 48,
	},
	{
		Name:   "bind",
		Number: 49,
	},
	{
		Name:   "listen",
		Number: 50,
	},
	{
		Name:   "getsockname",
		Number: 51,
	},
	{
		Name:   "getpeername",
		Number: 52,
	},
	{
		Name:   "socketpair",
		Number: 53,
	},
	{
		Name:   "setsockopt",
		Number: 54,
	},
	{
		Name:   "getsockopt",
		Number: 55,
	},
	{
		Name:   "clone",
		Number: 56,
	},
	{
		Name:   "fork",
		Number: 57,
	},
	{
		Name:   "vfork",
		Number: 58,
	},
	{
		Name:   "execve",
		Number: 59,
	},
	{
		Name:   "exit",
		Number: 60,
	},
	{
		Name:   "wait4",
		Number: 61,
	},
	{
		Name:   "kill",
		Number: 62,
	},
	{
		Name:   "uname",
		Number: 63,
	},
	{
		Name:   "semget",
		Number: 64,
	},
	{
		Name:   "semop",
		Number: 65,
	},
	{
		Name:   "semctl",
		Number: 66,
	},
	{
		Name:   "shmdt",
		Number: 67,
	},
	{
		Name:   "msgget",
		Number: 68,
	},
	{
		Name:   "msgsnd",
		Number: 69,
	},
	{
		Name:   "msgrcv",
		Number: 70,
	},
	{
		Name:   "msgctl",
		Number: 71,
	},
	{
		Name:   "fcntl",
		Number: 72,
	},
	{
		Name:   "flock",
		Number: 73,
	},
	{
		Name:   "fsync",
		Number: 74,
	},
	{
		Name:   "fdatasync",
		Number: 75,
	},
	{
		Name:   "truncate",
		Number: 76,
	},
	{
		Name:   "ftruncate",
		Number: 77,
	},
	{
		Name:   "getdents",
		Number: 78,
	},
	{
		Name:   "getcwd",
		Number: 79,
	},
	{
		Name:   "chdir",
		Number: 80,
	},
	{
		Name:   "fchdir",
		Number: 81,
	},
	{
		Name:   "rename",
		Number: 82,
	},
	{
		Name:   "mkdir",
		Number: 83,
	},
	{
		Name:   "rmdir",
		Number: 84,
	},
	{
		Name:   "creat",
		Number: 85,
	},
	{
		Name:   "link",
		Number: 86,
	},
	{
		Name:   "unlink",
		Number: 87,
	},
	{
		Name:   "symlink",
		Number: 88,
	},
	{
		Name:   "readlink",
		Number: 89,
	},
	{
		Name:   "chmod",
		Number: 90,
	},
	{
		Name:   "fchmod",
		Number: 91,
	},
	{
		Name:   "chown",
		Number: 92,
	},
	{
		Name:   "fchown",
		Number: 93,
	},
	{
		Name:   "lchown",
		Number: 94,
	},
	{
		Name:   "umask",
		Number: 95,
	},
	{
		Name:   "gettimeofday",
		Number: 96,
	},
	{
		Name:   "getrlimit",
		Number: 97,
	},
	{
		Name:   "getrusage",
		Number: 98,
	},
	{
		Name:   "sysinfo",
		Number: 99,
	},
	{
		Name:   "times",
		Number: 100,
	},
	{
		Name:   "ptrace",
		Number: 101,
	},
	{
		Name:   "getuid",
		Number: 102,
	},
	{
		Name:   "syslog",
		Number: 103,
	},
	{
		Name:   "getgid",
		Number: 104,
	},
	{
		Name:   "setuid",
		Number: 105,
	},
	{
		Name:   "setgid",
		Number: 106,
	},
	{
		Name:   "geteuid",
		Number: 107,
	},
	{
		Name:   "getegid",
		Number: 108,
	},
	{
		Name:   "setpgid",
		Number: 109,
	},
	{
		Name:   "getppid",
		Number: 110,
	},
	{
		Name:   "getpgrp",
		Number: 111,
	},
	{
		Name:   "setsid",
		Number: 112,
	},
	{
		Name:   "setreuid",
		Number: 113,
	},
	{
		Name:   "setregid",
		Number: 114,
	},
	{
		Name:   "getgroups",
		Number: 115,
	},
	{
		Name:   "setgroups",
		Number: 116,
	},
	{
		Name:   "setresuid",
		Number: 117,
	},
	{
		Name:   "getresuid",
		Number: 118,
	},
	{
		Name:   "setresgid",
		Number: 119,
	},
	{
		Name:   "getresgid",
		Number: 120,
	},
	{
		Name:   "getpgid",
		Number: 121,
	},
	{
		Name:   "setfsuid",
		Number: 122,
	},
	{
		Name:   "setfsgid",
		Number: 123,
	},
	{
		Name:   "getsid",
		Number: 124,
	},
	{
		Name:   "capget",
		Number: 125,
	},
	{
		Name:   "capset",
		Number: 126,
	},
	{
		Name:   "rt_sigpending",
		Number: 127,
	},
	{
		Name:   "rt_sigtimedwait",
		Number: 128,
	},
	{
		Name:   "rt_sigqueueinfo",
		Number: 129,
	},
	{
		Name:   "rt_sigsuspend",
		Number: 130,
	},
	{
		Name:   "sigaltstack",
		Number: 131,
	},
	{
		Name:   "utime",
		Number: 132,
	},
	{
		Name:   "mknod",
		Number: 133,
	},
	{
		Name:   "uselib",
		Number: 134,
	},
	{
		Name:   "personality",
		Number: 135,
	},
	{
		Name:   "ustat",
		Number: 136,
	},
	{
		Name:   "statfs",
		Number: 137,
	},
	{
		Name:   "fstatfs",
		Number: 138,
	},
	{
		Name:   "sysfs",
		Number: 139,
	},
	{
		Name:   "getpriority",
		Number: 140,
	},
	{
		Name:   "setpriority",
		Number: 141,
	},
	{
		Name:   "sched_setparam",
		Number: 142,
	},
	{
		Name:   "sched_getparam",
		Number: 143,
	},
	{
		Name:   "sched_setscheduler",
		Number: 144,
	},
	{
		Name:   "sched_getscheduler",
		Number: 145,
	},
	{
		Name:   "sched_get_priority_max",
		Number: 146,
	},
	{
		Name:   "sched_get_priority_min",
		Number: 147,
	},
	{
		Name:   "sched_rr_get_interval",
		Number: 148,
	},
	{
		Name:   "mlock",
		Number: 149,
	},
	{
		Name:   "munlock",
		Number: 150,
	},
	{
		Name:   "mlockall",
		Number: 151,
	},
	{
		Name:   "munlockall",
		Number: 152,
	},
	{
		Name:   "vhangup",
		Number: 153,
	},
	{
		Name:   "modify_ldt",
		Number: 154,
	},
	{
		Name:   "pivot_root",
		Number: 155,
	},
	{
		Name:   "_sysctl",
		Number: 156,
	},
	{
		Name:   "prctl",
		Number: 157,
	},
	{
		Name:   "arch_prctl",
		Number: 158,
	},
	{
		Name:   "adjtimex",
		Number: 159,
	},
	{
		Name:   "setrlimit",
		Number: 160,
	},
	{
		Name:   "chroot",
		Number: 161,
	},
	{
		Name:   "sync",
		Number: 162,
	},
	{
		Name:   "acct",
		Number: 163,
	},
	{
		Name:   "settimeofday",
		Number: 164,
	},
	{
		Name:   "mount",
		Number: 165,
	},
	{
		Name:   "umount2",
		Number: 166,
	},
	{
		Name:   "swapon",
		Number: 167,
	},
	{
		Name:   "swapoff",
		Number: 168,
	},
	{
		Name:   "reboot",
		Number: 169,
	},
	{
		Name:   "sethostname",
		Number: 170,
	},
	{
		Name:   "setdomainname",
		Number: 171,
	},
	{
		Name:   "iopl",
		Number: 172,
	},
	{
		Name:   "ioperm",
		Number: 173,
	},
	{
		Name:   "create_module",
		Number: 174,
	},
	{
		Name:   "init_module",
		Number: 175,
	},
	{
		Name:   "delete_module",
		Number: 176,
	},
	{
		Name:   "get_kernel_syms",
		Number: 177,
	},
	{
		Name:   "query_module",
		Number: 178,
	},
	{
		Name:   "quotactl",
		Number: 179,
	},
	{
		Name:   "nfsservctl",
		Number: 180,
	},
	{
		Name:   "getpmsg",
		Number: 181,
	},
	{
		Name:   "putpmsg",
		Number: 182,
	},
	{
		Name:   "afs_syscall",
		Number: 183,
	},
	{
		Name:   "tuxcall",
		Number: 184,
	},
	{
		Name:   "security",
		Number: 185,
	},
	{
		Name:   "gettid",
		Number: 186,
	},
	{
		Name:   "readahead",
		Number: 187,
	},
	{
		Name:   "setxattr",
		Number: 188,
	},
	{
		Name:   "lsetxattr",
		Number: 189,
	},
	{
		Name:   "fsetxattr",
		Number: 190,
	},
	{
		Name:   "getxattr",
		Number: 191,
	},
	{
		Name:   "lgetxattr",
		Number: 192,
	},
	{
		Name:   "fgetxattr",
		Number: 193,
	},
	{
		Name:   "listxattr",
		Number: 194,
	},
	{
		Name:   "llistxattr",
		Number: 195,
	},
	{
		Name:   "flistxattr",
		Number: 196,
	},
	{
		Name:   "removexattr",
		Number: 197,
	},
	{
		Name:   "lremovexattr",
		Number: 198,
	},
	{
		Name:   "fremovexattr",
		Number: 199,
	},
	{
		Name:   "tkill",
		Number: 200,
	},
	{
		Name:   "time",
		Number: 201,
	},
	{
		Name:   "futex",
		Number: 202,
	},
	{
		Name:   "sched_setaffinity",
		Number: 203,
	},
	{
		Name:   "sched_getaffinity",
		Number: 204,
	},
	{
		Name:   "set_thread_area",
		Number: 205,
	},
	{
		Name:   "io_setup",
		Number: 206,
	},
	{
		Name:   "io_destroy",
		Number: 207,
	},
	{
		Name:   "io_getevents",
		Number: 208,
	},
	{
		Name:   "io_submit",
		Number: 209,
	},
	{
		Name:   "io_cancel",
		Number: 210,
	},
	{
		Name:   "get_thread_area",
		Number: 211,
	},
	{
		Name:   "lookup_dcookie",
		Number: 212,
	},
	{
		Name:   "epoll_create",
		Number: 213,
	},
	{
		Name:   "epoll_ctl_old",
		Number: 214,
	},
	{
		Name:   "epoll_wait_old",
		Number: 215,
	},
	{
		Name:   "remap_file_pages",
		Number: 216,
	},
	{
		Name:   "getdents64",
		Number: 217,
	},
	{
		Name:   "set_tid_address",
		Number: 218,
	},
	{
		Name:   "restart_syscall",
		Number: 219,
	},
	{
		Name:   "semtimedop",
		Number: 220,
	},
	{
		Name:   "fadvise64",
		Number: 221,
	},
	{
		Name:   "timer_create",
		Number: 222,
	},
	{
		Name:   "timer_settime",
		Number: 223,
	},
	{
		Name:   "timer_gettime",
		Number: 224,
	},
	{
		Name:   "timer_getoverrun",
		Number: 225,
	},
	{
		Name:   "timer_delete",
		Number: 226,
	},
	{
		Name:   "clock_settime",
		Number: 227,
	},
	{
		Name:   "clock_gettime",
		Number: 228,
	},
	{
		Name:   "clock_getres",
		Number: 229,
	},
	{
		Name:   "clock_nanosleep",
		Number: 230,
	},
	{
		Name:   "exit_group",
		Number: 231,
	},
	{
		Name:   "epoll_wait",
		Number: 232,
	},
	{
		Name:   "epoll_ctl",
		Number: 233,
	},
	{
		Name:   "tgkill",
		Number: 234,
	},
	{
		Name:   "utimes",
		Number: 235,
	},
	{
		Name:   "vserver",
		Number: 236,
	},
	{
		Name:   "mbind",
		Number: 237,
	},
	{
		Name:   "set_mempolicy",
		Number: 238,
	},
	{
		Name:   "get_mempolicy",
		Number: 239,
	},
	{
		Name:   "mq_open",
		Number: 240,
	},
	{
		Name:   "mq_unlink",
		Number: 241,
	},
	{
		Name:   "mq_timedsend",
		Number: 242,
	},
	{
		Name:   "mq_timedreceive",
		Number: 243,
	},
	{
		Name:   "mq_notify",
		Number: 244,
	},
	{
		Name:   "mq_getsetattr",
		Number: 245,
	},
	{
		Name:   "kexec_load",
		Number: 246,
	},
	{
		Name:   "waitid",
		Number: 247,
	},
	{
		Name:   "add_key",
		Number: 248,
	},
	{
		Name:   "request_key",
		Number: 249,
	},
	{
		Name:   "keyctl",
		Number: 250,
	},
	{
		Name:   "ioprio_set",
		Number: 251,
	},
	{
		Name:   "ioprio_get",
		Number: 252,
	},
	{
		Name:   "inotify_init",
		Number: 253,
	},
	{
		Name:   "inotify_add_watch",
		Number: 254,
	},
	{
		Name:   "inotify_rm_watch",
		Number: 255,
	},
	{
		Name:   "migrate_pages",
		Number: 256,
	},
	{
		Name:   "openat",
		Number: 257,
	},
	{
		Name:   "mkdirat",
		Number: 258,
	},
	{
		Name:   "mknodat",
		Number: 259,
	},
	{
		Name:   "fchownat",
		Number: 260,
	},
	{
		Name:   "futimesat",
		Number: 261,
	},
	{
		Name:   "newfstatat",
		Number: 262,
	},
	{
		Name:   "unlinkat",
		Number: 263,
	},
	{
		Name:   "renameat",
		Number: 264,
	},
	{
		Name:   "linkat",
		Number: 265,
	},
	{
		Name:   "symlinkat",
		Number: 266,
	},
	{
		Name:   "readlinkat",
		Number: 267,
	},
	{
		Name:   "fchmodat",
		Number: 268,
	},
	{
		Name:   "faccessat",
		Number: 269,
	},
	{
		Name:   "pselect6",
		Number: 270,
	},
	{
		Name:   "ppoll",
		Number: 271,
	},
	{
		Name:   "unshare",
		Number: 272,
	},
	{
		Name:   "set_robust_list",
		Number: 273,
	},
	{
		Name:   "get_robust_list",
		Number: 274,
	},
	{
		Name:   "splice",
		Number: 275,
	},
	{
		Name:   "tee",
		Number: 276,
	},
	{
		Name:   "sync_file_range",
		Number: 277,
	},
	{
		Name:   "vmsplice",
		Number: 278,
	},
	{
		Name:   "move_pages",
		Number: 279,
	},
	{
		Name:   "utimensat",
		Number: 280,
	},
	{
		Name:   "epoll_pwait",
		Number: 281,
	},
	{
		Name:   "signalfd",
		Number: 282,
	},
	{
		Name:   "timerfd_create",
		Number: 283,
	},
	{
		Name:   "eventfd",
		Number: 284,
	},
	{
		Name:   "fallocate",
		Number: 285,
	},
	{
		Name:   "timerfd_settime",
		Number: 286,
	},
	{
		Name:   "timerfd_gettime",
		Number: 287,
	},
	{
		Name:   "accept4",
		Number: 288,
	},
	{
		Name:   "signalfd4",
		Number: 289,
	},
	{
		Name:   "eventfd2",
		Number: 290,
	},
	{
		Name:   "epoll_create1",
		Number: 291,
	},
	{
		Name:   "dup3",
		Number: 292,
	},
	{
		Name:   "pipe2",
		Number: 293,
	},
	{
		Name:   "inotify_init1",
		Number: 294,
	},
	{
		Name:   "preadv",
		Number: 295,
	},
	{
		Name:   "pwritev",
		Number: 296,
	},
	{
		Name:   "rt_tgsigqueueinfo",
		Number: 297,
	},
	{
		Name:   "perf_event_open",
		Number: 298,
	},
	{
		Name:   "recvmmsg",
		Number: 299,
	},
	{
		Name:   "fanotify_init",
		Number: 300,
	},
	{
		Name:   "fanotify_mark",
		Number: 301,
	},
	{
		Name:   "prlimit64",
		Number: 302,
	},
	{
		Name:   "name_to_handle_at",
		Number: 303,
	},
	{
		Name:   "open_by_handle_at",
		Number: 304,
	},
	{
		Name:   "clock_adjtime",
		Number: 305,
	},
	{
		Name:   "syncfs",
		Number: 306,
	},
	{
		Name:   "sendmmsg",
		Number: 307,
	},
	{
		Name:   "setns",
		Number: 308,
	},
	{
		Name:   "getcpu",
		Number: 309,
	},
	{
		Name:   "process_vm_readv",
		Number: 310,
	},
	{
		Name:   "process_vm_writev",
		Number: 311,
	},
	{
		Name:   "kcmp",
		Number: 312,
	},
	{
		Name:   "finit_module",
		Number: 313,
	},
	{
		Name:   "sched_setattr",
		Number: 314,
	},
	{
		Name:   "sched_getattr",
		Number: 315,
	},
	{
		Name:   "renameat2",
		Number: 316,
	},
	{
		Name:   "seccomp",
		Number: 317,
	},
	{
		Name:   "getrandom",
		Number: 318,
	},
	{
		Name:   "memfd_create",
		Number: 319,
	},
	{
		Name:   "kexec_file_load",
		Number: 320,
	},
	{
		Name:   "bpf",
		Number: 321,
	},
	{
		Name:   "execveat",
		Number: 322,
	},
	{
		Name:   "userfaultfd",
		Number: 323,
	},
	{
		Name:   "membarrier",
		Number: 324,
	},
	{
		Name:   "mlock2",
		Number: 325,
	},
	{
		Name:   "copy_file_range",
		Number: 326,
	},
	{
		Name:   "preadv2",
		Number: 327,
	},
	{
		Name:   "pwritev2",
		Number: 328,
	},
	{
		Name:   "pkey_mprotect",
		Number: 329,
	},
	{
		Name:   "pkey_alloc",
		Number: 330,
	},
	{
		Name:   "pkey_free",
		Number: 331,
	},
	{
		Name:   "statx",
		Number: 332,
	},
	{
		Name:   "io_pgetevents",
		Number: 333,
	},
	{
		Name:   "rseq",
		Number: 334,
	},
	{
		Name:   "pidfd_send_signal",
		Number: 424,
	},
	{
		Name:   "io_uring_setup",
		Number: 425,
	},
	{
		Name:   "io_uring_enter",
		Number: 426,
	},
	{
		Name:   "io_uring_register",
		Number: 427,
	},
	{
		Name:   "open_tree",
		Number: 428,
	},
	{
		Name:   "move_mount",
		Number: 429,
	},
	{
		Name:   "fsopen",
		Number: 430,
	},
	{
		Name:   "fsconfig",
		Number: 431,
	},
	{
		Name:   "fsmount",
		Number: 432,
	},
	{
		Name:   "fspick",
		Number: 433,
	},
	{
		Name:   "pidfd_open",
		Number: 434,
	},
	{
		Name:   "clone3",
		Number: 435,
	},
	{
		Name:   "close_range",
		Number: 436,
	},
	{
		Name:   "openat2",
		Number: 437,
	},
	{
		Name:   "pidfd_getfd",
		Number: 438,
	},
	{
		Name:   "faccessat2",
		Number: 439,
	},
	{
		Name:   "process_madvise",
		Number: 440,
	},
	{
		Name:   "epoll_pwait2",
		Number: 441,
	},
	{
		Name:   "mount_setattr",
		Number: 442,
	},
	{
		Name:   "quotactl_fd",
		Number: 443,
	},
	{
		Name:   "landlock_create_ruleset",
		Number: 444,
	},
	{
		Name:   "landlock_add_rule",
		Number: 445,
	},
	{
		Name:   "landlock_restrict_self",
		Number: 446,
	},
	{
		Name:   "memfd_secret",
		Number: 447,
	},
	{
		Name:   "process_mrelease",
		Number: 448,
	},
	{
		Name:   "futex_waitv",
		Number: 449,
	},
	{
		Name:   "set_mempolicy_home_node",
		Number: 450,
	},
	{
		Name:   "cachestat",
		Number: 451,
	},
	{
		Name:   "fchmodat2",
		Number: 452,
	},
	{
		Name:   "map_shadow_stack",
		Number: 453,
	},
	{
		Name:   "futex_wake",
		Number: 454,
	},
	{
		Name:   "futex_wait",
		Number: 455,
	},
	{
		Name:   "futex_requeue",
		Number: 456,
	},
	{
		Name:   "statmount",
		Number: 457,
	},
	{
		Name:   "listmount",
		Number: 458,
	},
	{
		Name:   "lsm_get_self_attr",
		Number: 459,
	},
	{
		Name:   "lsm_set_self_attr",
		Number: 460,
	},
	{
		Name:   "lsm_list_modules",
		Number: 461,
	},
}
